# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'function convolve in C++ version
#'
#'The function to calculate the convolution of two vectors implemented by C++. It
#' plays as a performance comparison with \code{\link{convolveR}}.
#'
#'@param a,b two vectors to be convolved
#'
#'@return a vector as the convolution of vectors a and b
#'
#'@export
convolveCpp <- function(a, b) {
    .Call('rtest_convolveCpp', PACKAGE = 'rtest', a, b)
}

#'Function timesTwo
#'
#'the function to multipy x by 2
#'
#'@param x a vector
#'@return the vector x*2
#'@examples
#'timesTwo(10)
#'@export
timesTwo <- function(x) {
    .Call('rtest_timesTwo', PACKAGE = 'rtest', x)
}

