# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'Function timesTwo
#'
#'the function to multipy x by 2
#'
#'@param x a vector
#'@return the vector x*2
#'@examples
#'timesTwo(10)
#'@export
timesTwo <- function(x) {
    .Call('rtest_timesTwo', PACKAGE = 'rtest', x)
}

